name: Nifty-Alarm

on:
  schedule:
    - cron: '0 0 * * *'  # 이 설정이 한국 시간 오전 9시입니다!
  workflow_dispatch:

env:
      TZ: Asia/Seoul  # 이 한 줄이 시간을 한국으로 맞춰줍니다!
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 필요한 도구 설치
        run: pip install yfinance requests
      - name: 실행
        run: python main.py
